---
- name: Install terminator htop ansible-lint
  become: yes
  package:
    name:
      - terminator
      - htop
      - ansible-lint
    state: present

- name: Stop unnecessary process
  systemd:
    state: stopped
    name: snap