---
- name: Install terminator ansible-lint python3-venv
  package:
    name:
      - terminator
      - ansible-lint
      - python3-venv
      - htop
      - git
    state: present

- name: Install gcloud aws az tf kubectl helm pycharm htop with option --classic
  snap:
    name:
      - google-cloud-sdk
      - aws-cli
      - kubectl
      - terraform
      - helm
      - pycharm-community
    classic: yes

- name: Install azure-cli
  snap:
    name:
      - azure-cli
    classic: yes
    channel: latest/edge
