---
- name: Create user
  user :
    name: "{{ username }}"
    password: "{{ password  | password_hash('sha512') }}"
    shell: /bin/bash
    home:  /home/{{ username }}
    group: root

- name: Install fish
  package:
    name: fish
    state: present

- name: Clone oh-my-fish repo
  git:
    repo: "https://github.com/oh-my-fish/oh-my-fish"
    dest: "/tmp/omf"
    clone: yes

- name: Install oh-my-fish
  become_user: "{{ item }}"
  command: /tmp/omf/bin/install -y --offline --noninteractive
  with_items: "{{ users_list }}"

- name: Configure theme yimmy for oh-my-fish
  become_user: "{{ item }}"
  command: fish -c "omf install yimmy"
  with_items: "{{ users_list }}"

# chsh --shell /usr/bin/fish
- name: Change default shell to fish for users
  user:
    name: "{{ item }}"
    shell: /usr/bin/fish
    home:  /home/{{ item }}
  with_items: "{{ users_list | reject('search','root') | list }}"

- name: Change default shell for root
  user:
    name: root
    shell: /usr/bin/fish
    home:  /root