---
- name: Install prerequisites
  package:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg-agent
    state: present

- name: Add Docker GPG key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg

- name: Add Docker APT repository
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable

- name: Install Docker
  package:
    name: docker-ce
    update_cache: yes

- name: Create Docker group
  group:
    name: docker
    state: present

- name: Add current user to Docker group
  user:
    name:  "{{ item }}"
    groups: docker
    append: yes
  with_items: "{{ users_list }}"

- name: Download docker-compose
  get_url:
    url: https://github.com/docker/compose/releases/download/1.24.1/docker-compose-Linux-x86_64
    dest: /usr/local/bin/docker-compose
    force: no
    mode: 0755

- name: Everybody can run docker
  file:
    path: /var/run/docker.sock
    mode: '777'
